BWSR-373: Add fragment scheme support
Hearst-Hatchery/graphql-php-query-builder pull request #4
Opened 2018-11-05 23:10 UTC by dee2716

2018-11-06 22:12 UTC, felton commented
@dee2716 Can you post an example of how to use Field/Fragment to build a complex query?

2018-11-06 22:23 UTC, felton commented on src/QueryBuilder.php
> +                    $type = gettype($type) === 'string' ? '["' . implode('","', $type) . '"]' : '[' . implode(',', $type) . ']' ;
👍

2018-11-07 20:00 UTC, dee2716 commented on src/QueryBuilder.php
> +     * renderQueryObjectPrettify loop through given query array and convert into graphQL query format string
yes. I missed this one. I'm going to update the description now.

2018-11-07 20:52 UTC, felton requested changes
Looks good, just one thing about the prettyfier, and we talked offline about fields

2018-11-07 20:52 UTC, felton commented on src/Field.php
> +        $fieldQuery .= $prettify === true ? $this->renderQueryObjectPrettify($this->queryObject, $depth) . str_repeat("\t", $depth - 1) : $this->renderQueryObject($this->queryObject);
If someone tries to prettify a complex query, there's risk of it failing if they don't specify the depth properly. Can you add a comment in the docbloc explaining this. Perhaps we can revisit this with a prettifier that runs after the query is built.

2018-11-07 22:06 UTC, felton approved these changes
looks great! 👍

2018-11-09 20:44 UTC, merged